Update rofetch
Added option flags. See -h/--help and -v/--version for changelog

diff --git a/rofetch b/rofetch
--- a/rofetch
+++ b/rofetch
@@ -4,16 +4,17 @@
 # Color variables
 VERME="\033[1;31m"
 VERME2="\033[0;31m"
+ERROR_="\033[0;31m"
 VERDE="\033[1;32m"
 ROXO="\033[1;95m"
 FIM="\033[0;00m"
 
 
-# Checking if dependencies are installed in the first execution:
-CHECK_DEP(){
+# Checking if dependencies are installed in the first shell execution:
+function CHECK_DEP {
   local DEPEN_="ip free uname awk grep cut tr ps curl jq"
 
-  printf "${ROXO}+ First execution, checking for ${FIM}${VERDE}Rofetch${ROXO} dependencies...${FIM}\n"
+  printf "${ROXO}+ First shell execution, checking for ${FIM}${VERDE}Rofetch${ROXO} dependencies...${FIM}\n"
   for CMD_ in DEPEN_; do
     if command -v "$CMD_" >/dev/null 2>&1; then
       printf "[Error]: Missing dependency $CMD_\n"
@@ -24,7 +25,8 @@ CHECK_DEP(){
   touch "$MARKER_FILE"
 }
 
-# Checking for marker file's existence:
+# Checking for marker file's existence and CONFIG file:
+CONFIG_COLOR_FILE="$HOME/.config/rofetch-color-config"
 MARKER_FILE="/tmp/.rofetch-first-execution"
 [ ! -f "$MARKER_FILE" ]&& CHECK_DEP
 
@@ -40,15 +42,22 @@ fi
 
 # Option flag functions:
 # Help message (-h/--help)
-HELP_(){
+function HELP_ {
   echo -e "\nUsage: ${0##*/} [OPTION] [-d]\n\n\
-  Options:\n\
+  OPTIONS:\n\
     -h | --help                  :: Shows this help message.\n\
+    -v | --version               :: Shows current program version with changelog.\n\
     -b | --banner /path/to/file  :: Set custom ASCII art banner. Must be no more than 15 lines.\n\
     -d | --debug                 :: Runs the program with bash's debug mode.\n\
                                     Debug flag MUST be the last argument!\n\
                                     Example: ./rofetch -b ascii.txt -d\n\
-  Description:\n\
+    BANNER OPTIONS:
+    -bc  | --banner-color \"...\"    :: Temporaly changes banner color to a set of colors in a list.
+                                      Use -bc \"x\" to see list of colors\n\
+    -sbc | --set-banner-color \"...\":: Permanently changes banner color and storages in a .config file\n\
+    --reset-banner-color           :: Resets banner color to default.\n\
+
+  DESCRIPTION:\n\
   Rofetch is a command line interface system information tool inspired by neofetch\n\
   written fully in bash script. Its main purpose is to be fast, reliable and clean.\n\
   Rofetch displays information next to a default \"R\" ASCII art but the art can also\n\
@@ -57,14 +66,14 @@ HELP_(){
 
 
   Improvements ideas and bug reports are welcome and can be solicited at:\n\
-  https://github.com/dylanaraps/neofetch/issues\n\
+  https://github.com/RodricBr/rofetch/issues\n\
   "
   exit 0
 }
 
 # Version message (-v/--version)
-VERSION_(){
-  echo -e "\nVersion: 3.2\n\
+function VERSION_ {
+  echo -e "\nVersion: 4.0\n\
   + Added more compability for Debian based distros & UNIX/POSIX systems.\n\
   + Detect VM and DE/WM are more dynamic.\n\
   + \"r.txt\" file with default banner is no longer needed.\n\
@@ -72,9 +81,11 @@ VERSION_(){
   + Rewrote the whole code and made it more legible for programmers.\n\
   + Checks for dependencies on the first execution.\n\
   Marker file \".rofetch-first-execution\" will be created in \"/tmp/\" directory.\n\
+  + New temporary changeable banner color\n\
+  + New permanent banner color configuration file ($HOME/.config/rofetch-color-config)\n\
+  + New reset default banner color flag\n\
   - Inspiration quotes variable was commented out and will be a WIP for now\n\
   since it's been consuming a little bit too much of user execution time.\n\
-  - Displaying now Font Name with Font Size next to it.\n\
   "
   exit 0
 }
@@ -82,8 +93,69 @@ VERSION_(){
 
 # Calling the help or version function if flags are being called
 [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]&& HELP_
-[[ "$1" == "-v" ]] || [[ "$1" == "--version" ]] && VERSION_
+[[ "$1" == "-v" ]] || [[ "$1" == "--version" ]]&& VERSION_
+#[[ "$1" == "-bc" ]] || [[ "$1" == "--banner-color" ]]&& VERME2="$2"
 
+declare -A STRING_COLORS=(
+  [green]="\033[0;32m"
+  [light green]="\033[1;32m"
+  [red]="\033[0;31m"
+  [light red]="\033[1;31m"
+  [blue]="\033[0;34m"
+  [light blue]="\033[1;34m"
+  [yellow]="\033[0;33m"
+  [light yellow]="\033[1;33m"
+  [cyan]="\033[38;5;51m"
+  [light cyan]="\033[38;5;159m"
+  [purple]="\033[38;5;57m"
+  [light purple]="\033[38;5;135m"
+  [white]="\033[38;5;255m"
+  [grey]="\033[38;5;244m"
+  [black]="\033[38;5;232m" #\033[38;5;233m # lesser black
+)
+
+if [[ -f "$CONFIG_COLOR_FILE" ]]; then
+  SAVED_COLOR=$(<"$CONFIG_COLOR_FILE")
+  if [[ -n "${STRING_COLORS[$SAVED_COLOR]}" ]]; then
+    VERME2="${STRING_COLORS[$SAVED_COLOR]}"
+  fi
+fi
+
+if [[ -f "$MARKER_FILE" ]]; then
+  COLOR=$(<"$MARKER_FILE")
+fi
+
+echo "$COLOR" > "$MARKER_FILE"
+
+if [[ "$1" == "-bc" ]] || [[ "$1" == "--banner-color" ]]; then
+  if [[ -n "${STRING_COLORS[$2]}" ]]; then
+    VERME2="${STRING_COLORS[$2]}"
+  else
+    printf "${ERROR_}[Error]:${FIM} Invalid color \"%s\"! Available colors: %s\n" "$2" \
+      "$(printf "%s\n" "${!STRING_COLORS[@]}" \
+      | sort | while read -r c; do printf "%s, " "$c"; done \
+      | sed 's/, $//')"
+    exit 1
+  fi
+fi
+
+if [[ "$1" == "-sbc" ]] || [[ "$1" == "--set-banner-color" ]]; then
+  if [[ -n "${STRING_COLORS[$2]}" ]]; then
+    mkdir -p "$(dirname "$CONFIG_COLOR_FILE")"
+    echo "$2" > "$CONFIG_COLOR_FILE"
+    VERME2="${STRING_COLORS[$2]}"
+  else
+    printf "${ERROR_}[Error]:${FIM} Invalid color \"$2\"! Available colors: ${!STRING_COLORS[*]}\n"
+    exit 1
+  fi
+fi
+
+# Resets to default banner color
+if [[ "$1" == "--reset-banner-color" ]]; then
+  rm -f "$CONFIG_COLOR_FILE"
+  #printf "${INFO_}Banner color reset to default.${FIM}\n"
+  exit 0
+fi
 
 # Other variables:
 export LANG=C.UTF-8
@@ -101,7 +173,7 @@ export LANG=C.UTF-8
 
 # Main Functions:
 # Checks if user is running on a standardize system or not
-OS_DETECT_FUNC(){
+function OS_DETECT_FUNC {
   if [[ ! -f "/etc/lsb-release" ]]; then
     # slower: grep "PRETTY_" /etc/os-release | cut -d "=" -f2 | tr -d '"'
     awk -F= '/^PRETTY_NAME=/ { gsub(/"/, "", $2); print $2 }' /etc/os-release
@@ -111,13 +183,15 @@ OS_DETECT_FUNC(){
   fi
 }
 
-# Fetching font name and font size
-FONT_FUNC(){
+# Getting font name
+function FONT_FUNC {
+  # slower: echo -ne "$TERM ($(tty))) / ($(grep "FONTFACE" /etc/default/console-setup | cut -d "=" -f2 | tr -d '"'))"
+  #echo -ne "$TERM ($(tty)) / ($(awk -F= '/^FONTFACE=/ { gsub(/"/, "", $2); print $2 }' /etc/default/console-setup))"
   echo -ne "$TERM ($(tty)) / ($(awk -F= '/^(FONTFACE|FONTSIZE)=/ { gsub(/"/, "", $2); a[++i]=$2 } END { printf "%s %s", a[1], a[2] }' /etc/default/console-setup))"
 }
 
-# Fetching local ipv4 address and checking if the user has access to the internet
-IPV4_FUNC(){
+# Getting local ipv4 address and checking if the user has access to the internet
+function IPV4_FUNC {
   local IP_CMD=$(ip route get 1.1.1.1 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')
   if ! ping -W 2 -c 1 8.8.8.8 &>/dev/null; then
     printf "$IP_CMD ${VERME}(Disconnected)${FIM}"
@@ -126,34 +200,31 @@ IPV4_FUNC(){
   fi
 }
 
-# Fetching kernel information
-KERNEL_FUNC(){
+# Getting kernel information
+function KERNEL_FUNC {
   uname -smr
 }
 
-# Fetching up-time
-UPTIME_FUNC(){
+# Getting up time
+function UPTIME_FUNC {
   echo "$(awk '{print int($1/3600)" hours "int(($1%3600)/60)" minutes"}' /proc/uptime)"
 }
 
-# Fetching amount of packages installed using dpkg
-PACK_AMOUNT(){
-  dpkg -l | grep -c '^ii'
-}
-
-# Fetching user's memory usage information
-MEMUSE_FUNC(){
+# Getting user's memory usage information
+function MEMUSE_FUNC {
   free -m | awk 'NR==2{printf "\033[1;31mMemory Usage\033[0m: \t %s / %sMiB (%.2f%%)\n", $3,$2,$3*100/$2 }'
 }
 
-# Fetching shell name and version
-SHELL_FUNC(){
+# Getting shell name and version
+function SHELL_FUNC {
   VERR_=$($SHELL --version); echo ${VERR_%%(*}
+
   # Matches only before the "("
+
 }
 
-# Fetching DE Name
-CHECK_VM(){
+# Getting DE Name
+function CHECK_VM {
   # Trying /sys/class/dmi/id if available
   if [[ -r /sys/class/dmi/id/sys_vendor && -r /sys/class/dmi/id/product_name ]]; then
     vendor=$(< /sys/class/dmi/id/sys_vendor)
@@ -198,7 +269,7 @@ CHECK_VM(){
 }
 
 
-DE_WM_FUNC(){
+function DE_WM_FUNC {
   local DE_ WM_
 
   # Detect DE using environment variables
@@ -237,7 +308,7 @@ DE_WM_FUNC(){
 
 # Banner functionality:
 # If banner flag is set by the user, read banner file and store into an array
-READ_BANNER_FUNC(){
+function READ_BANNER_FUNC {
   lines=()
   while IFS= read -r line; do
     lines+=("$line")
@@ -254,10 +325,10 @@ if [[ "$1" == "-b" || "$1" == "--banner" ]]; then
     READ_BANNER_FUNC "$ARQ_"
   else
     if [[ -f "$ARQ_" ]]; then
-      printf "${VERME2}[Error]:${FIM} Banner file \"$ARQ_\" was not found!\nQuitting...\n"
+      printf "${ERROR_}[Error]:${FIM} Banner file \"$ARQ_\" was not found!\nQuitting...\n"
       exit 1
     else
-      printf "${VERME2}[Error]:${FIM} Banner option requires an existing file as argument!\nQuitting...\n"
+      printf "${ERROR_}[Error]:${FIM} Banner option requires an existing file as argument!\nQuitting...\n"
       exit 1
     fi
   fi
@@ -298,11 +369,11 @@ echo -e "${VERME2}${lines[5]}  ${VERME}IPv4 (Local)${FIM}:\t $(IPV4_FUNC)"
 echo -e "${VERME2}${lines[6]}  ${VERME}Kernel${FIM}:\t\t $(KERNEL_FUNC)"
 echo -e "${VERME2}${lines[7]}  ${VERME}Uptime${FIM}:\t\t $(UPTIME_FUNC)"
 echo -e "${VERME2}${lines[8]}  $(MEMUSE_FUNC)"
-echo -e "${VERME2}${lines[9]}  ${VERME}Packages${FIM}:\t\t $(PACK_AMOUNT)"
-echo -e "${VERME2}${lines[10]}  ${VERME}Shell${FIM}:\t\t $(SHELL_FUNC)"
-echo -e "${VERME2}${lines[11]}  ${VERME}DE & WM${FIM}:\t\t $(DE_WM_FUNC)"
-echo -e "${VERME2}${lines[12]}${FIM}"
-echo -e "${VERME2}${lines[13]}  ${ROXO}${MSG_//\"}${FIM}"
+echo -e "${VERME2}${lines[9]}  ${VERME}Shell${FIM}:\t\t $(SHELL_FUNC)"
+echo -e "${VERME2}${lines[10]}  ${VERME}DE & WM${FIM}:\t\t $(DE_WM_FUNC)"
+echo -e "${VERME2}${lines[11]}${FIM}"
+echo -e "${VERME2}${lines[12]}  ${ROXO}${MSG_//\"}${FIM}"
+echo -e "${VERME2}${lines[13]}${FIM}"
 echo -e "${VERME2}${lines[14]}${FIM}"
 
 unset MSG_ VERME VERME2 VERDE ROXO FIM CHECK_VM_
